import Head from 'next/head'

import styles from '../../styles/Home.module.css'
import {useRouter} from "next/router";


export default function MyDinamicPage() {

    const router = useRouter();
    const paramExample = router.query.param;

    const {param} = router.query;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />

            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    MyDinamicPage paramExample {paramExample}

                </h1>
                <h1 className={styles.title}>
                    MyDinamicPage param {param}

                </h1>


            </main>

        </div>
    )
}
